### ISSUE TITLE
Add the `GameworldBuilder` 

### ISSUE THREAD

**Issue by daskycodes** [The-Microservice-Dungeon/map#14]
In #10 we created our `Gameworld` model. In #11 we created our `Planet` model.

## What

We can now start to build our `GameworldBuilder` which will be the base of our `POST /gameworlds` endpoint.

We can expect to receive the following post request in our controller:

```bash
curl --request POST \
  --url http://127.0.0.1:3000/gameworlds \
  --header 'Content-Type: application/json' \
  --data '
{ 
	"gameworld": {
		"player_amount": 100,
		"round_amount": 100
	}
}'
```

The number of `Planets` belonging to the `Gameworld` should be dependant on the `player_amount` and `round_amount`

## How

Create a new class `GameworldBuilder` 

The builder should initialize a `Gameworld` with default `Planets`

For easyness of associating neighbouring `Planets` we included a `x` and `y` field on each `Planet`.

To add a neighbouring planet to a planet we can simply call `planet.add_neighbour(neighbour)` on the given planet.

We should also make sure to test it properly. Here a visual terminal output might be useful for debugging.

The Enumerable module will be helpful https://ruby-doc.org/core-3.0.2/Enumerable.html
Also maybe check the builder pattern if it can be applied https://ieftimov.com/post/refactoring-builder-pattern/

## TODO

- [x] https://github.com/The-Microservice-Dungeon/map/pull/27
- [x] https://github.com/The-Microservice-Dungeon/map/issues/28
- [x] https://github.com/The-Microservice-Dungeon/map/issues/40
- [x] https://github.com/The-Microservice-Dungeon/map/issues/41
- [x] https://github.com/The-Microservice-Dungeon/map/issues/37
- [x] https://github.com/The-Microservice-Dungeon/map/issues/36
- [x] https://github.com/The-Microservice-Dungeon/map/issues/42
- [x] Write specs to test the whole thing
- [x] https://github.com/The-Microservice-Dungeon/map/issues/48

## How the API might look like
```ruby
player_amount = 100
round_amount = 1000

gameworld_builder = GameworldBuilder.new(player_amount, round_amount)

gameworld_builder.create_spawns
gameworld_builder.create_spacestations
gameworld_builder.add_coal_resources
gameworld_builder.add_iron_resources
gameworld_builder.add_gem_resources
gameworld_builder.add_gold_resources
gameworld_builder.add_platin_resources
gameworld_builder.add_movement_difficulty
gameworld_builder.delete_random_planets
gameworld_builder.finalize
```
