### ISSUE TITLE
Include the updating of `Planets` to `planet_type: spacestation` in `GameworldBuilder`

### ISSUE THREAD

**Issue by daskycodes** [The-Microservice-Dungeon/map#36]
Continuation of #31 
Part of #14

What
In our GameworldBuilder we do want to set a given amount of planets to planet_type spacestation. This issue will be about creating the spacestation builder method.

Think about where the spacestations should be on the planet and how to determine the position (x, y),
Do also think about the amount of `spacestations` we want to have based on the player amount
We should also apply the `recharge_multiplicator` on the `spacestations`

Executing the `SpacestationCreation` will be part of another issue

```ruby
player_amount = 50
round_amount = 1000

gameworld_builder = GameworldBuilder.new(player_amount, round_amount)
gameworld_builder.create_spacestations

spacestation_count = gameworld_builder.gameworld.planets.count { |p| p.planet_type == 'spacestation' }
expect(spacestation_count).to eq(?)
```

## TODO

- [x] Add the `GameworldBuilder.create_spacestations` method
- [x] Make sure that planet's are turned to planet_type spacestation
- [x] Make sure that the planet's recharge multiplicator is changed accordingly
- [x] Write specs
- [ ] Attach an image of the terminal from `GameworldPrinter.print_gameworld(gameworld)`
