### ISSUE TITLE
Add `resources` to `planets` in `GameworldBuilder`

### ISSUE THREAD

**Issue by daskycodes** [The-Microservice-Dungeon/map#42]
## What
Part of our `GameworldBuilder` is to allocate all the resources on the planets.

## TODO

- [x] Add the `GameworldBuilder.add_coal_resources` method
- [x] Add the `GameworldBuilder.add_iron_resources` method
- [x] Add the `GameworldBuilder.add_gem_resources` method
- [x] Add the `GameworldBuilder.add_gold_resources` method
- [x] Add the `GameworldBuilder.add_platin_resources` method
- [x] Write specs
- [ ] Attach an image of the terminal from `GameworldPrinter.print_gameworld(gameworld)`
