### ISSUE TITLE
Create a html view to visualise a `Gameworld`

### ISSUE THREAD

**Issue by Tristan-Steffen** [The-Microservice-Dungeon/map#61]
## what

create a visual display of a gameworld with as much detail as possible

## todo

- [x] create a working route to see all gameworlds in the databas
- [x] add a button to create new gameworlds
- [x] once you click a gameworld you go to the display page of said world
- [x] create a view that renders the basic layout of the gameworld
- [x] let each planet show what energy cost it has
- [x] let each planet show if is a spawn or spacestation
- [x] let each planet show if/which resource it has

**Comment by Tristan-Steffen** [comment]
## what

create a visual display of a gameworld with as much detail as possible

## todo

- [ ] create a working route to see all gameworlds in the databas
- [ ] add a button to create new gameworlds
- [ ] once you click a gameworld you go to the display page of said world
- [ ] create a view that renders the basic layout of the gameworld
- [ ] let each planet show what energy cost it has
- [ ] let each planet show if is a spawn or spacestation
- [ ] let each planet show if/which resource it has
