### ISSUE TITLE
Implement the delete_planets_functionallity

### ISSUE THREAD

**Issue by Tristan-Steffen** [The-Microservice-Dungeon/map#67]
## what

implement a function into the gameworld_builder that deletes a fix amount of planets randomly from the gameworld and have it work with existing functions like resource creation and space station creation

## todo

- [x] create a function in gamewolrd_builder to delete planets
- [x] add a function in the gameworlds_web view that checks for and displays the deleted planets
- [x] add tests for the planet removing function

**Comment by Tristan-Steffen** [comment]
## what

implement a function into the gameworld_builder that deletes a fix amount of planets randomly from the gameworld and have it work with existing functions like resource creation and space station creation

## todo

- [x] create a function in gamewolrd_builder to delete planets
- [ ] add a function in the gameworlds_web view that checks for and displays the deleted planets
- [ ] add tests for the planet removing function
- [ ] update all previous tests to incorporate the deletion of planets

**Comment by Tristan-Steffen** [comment]
the deletion of planets now works by adding an extra planet_type to the planet model called "empty". That way they are still inside the database, which makes it easier to display them in the view.

We will have to create a new finalize_map function which erases the neighbors of planets once the world is generated.
