### ISSUE TITLE
create finalize_map function

### ISSUE THREAD

**Issue by Tristan-Steffen** [The-Microservice-Dungeon/map#68]
## what
we have to create a finalize_map function that deletes the neighbors of planets with a `deleted_at`. This function should be called after all edits to the world have been made. Since we want to make some degree of manual changes to the map, this functions should be called after those manual changes have been made.

## todo
- [ ] create a finallize_map function
- [ ] create tests for that function
- [ ] make that function manually available? Or somehow activate it once the editing process of the map is complete?

**Comment by daskycodes** [comment]
Lets close this issue for now since the `GameworldBuilder.neighbour_planets` method already doesn't set the neighbours for those planets.

So if we call the `neighbour_planets` function as last step everything is fine.

In the planet controller we also simply return 
```ruby
    gameworld = Gameworld.find_by(status: 'active')
    @planets = Planet.where(gameworld_id: gameworld.id, deleted_at: nil)
```

This way deleted planets and planets for inative gameworlds are not shown.
