### ISSUE TITLE
Remove `ResourceType` model and add it as enum field

### ISSUE THREAD

**Issue by daskycodes** [The-Microservice-Dungeon/map#71]
## What
The `ResourceType` model currently is just a container for names. We can refactor this significantly.

## How
Lets remove the `ResourceType` model and add a new field to the `Resource` model `resource_type`

## TODO
- [x] Remove `ResourceType` model, controllers, views etc.
- [x] Add `Resource.resource_type` field as enum
- [x] Refactor code to work with the new field
- [x] Write specs
